version: '3.8'

services:
  eventhub-api:
    build:
      context: .
      dockerfile: eventhub-api/Dockerfile
    image: eventhub-api-v2:latest
    container_name: eventhub-api-v2
    env_file:
      - .env
    environment:
      - DB_URL=jdbc:postgresql://db:5432/eventhubdb
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - eventhub-net
      - proxy-net

  eventhub-payments:
    build:
      context: .
      dockerfile: eventHub-payments/Dockerfile
    image: eventhub-payments-v2:latest
    container_name: eventhub-payments-v2
    env_file:
      - .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - eventhub-net

  db:
    image: postgres:16-alpine
    container_name: eventhub-db-v2
    env_file:
      - .env
    environment:
      - POSTGRES_DB=eventhubdb
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - eventhub-net

  mongodb:
    image: mongo:7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=eventhub-payments
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - eventhub-net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: eventhub-rabbitmq-v2
    ports:
      - "15672:15672"
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - eventhub-net

volumes:
  postgres_data:
  mongodb_data:

networks:
  eventhub-net:
  proxy-net:
    external: true