name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Login to Docker Hub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: .
          file: eventhub-api/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/eventhub-api:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/eventhub-api:latest

      - name: Build and push Payments
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: .
          file: eventHub-payments/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/eventhub-payments:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/eventhub-payments:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Update docker-compose.yml with Docker Hub images
        run: |
          sed -i "s|image: eventhub-api-v2:latest|image: ${{ secrets.DOCKER_USERNAME }}/eventhub-api:${{ github.sha }}|g" docker-compose.yml
          sed -i "s|image: eventhub-payments-v2:latest|image: ${{ secrets.DOCKER_USERNAME }}/eventhub-payments:${{ github.sha }}|g" docker-compose.yml

      - name: Copy docker-compose and monitoring config to VPS
        uses: appleboy/scp-action@917f8b81dfc1ccd331fef9e2d61bdc6c8be94634 # v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "docker-compose.yml,monitoring"
          target: "/home/deploy/eventhub-v2"
          overwrite: true

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@029f5b4aeeeb58fdfe1410a5d17f967dacf36262 # v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            mkdir -p /home/deploy/eventhub-v2
            cd /home/deploy/eventhub-v2

            # Create .env file dynamically from a single GitHub Secret
            cat << 'EOF' > .env
            ${{ secrets.ENV_PRODUCTION }}
            EOF

            docker compose pull
            docker compose up -d --remove-orphans --no-build
